# Generated by Django 2.1.12 on 2019-09-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('job_type', models.CharField(max_length=50, null=True)),
                ('headquarters', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(max_length=50, null=True)),
                ('apply_link', models.CharField(max_length=50, null=True)),
                ('job_description', models.TextField(null=True)),
            ],
        ),
    ]
