# Generated by Django 2.1.12 on 2019-09-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobs_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='is_featured',
            field=models.BooleanField(null=True),
        ),
    ]
