# Generated by Django 2.1.12 on 2019-10-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobs_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
