# Generated by Django 2.2.4 on 2019-10-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20191001_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='tags',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
