# Generated by Django 2.1.12 on 2019-10-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20191006_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='slugTitle',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
