# Generated by Django 2.2.4 on 2019-10-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_jobs_slugtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
