# Generated by Django 2.1.12 on 2019-11-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20191007_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='slugTitle',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
