# Generated by Django 2.1.12 on 2019-11-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20191111_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
