# Generated by Django 2.1.12 on 2019-10-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
