# Generated by Django 2.1.12 on 2019-09-27 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/categories/'),
            preserve_default=False,
        ),
    ]
