# Generated by Django 2.1.12 on 2019-10-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_cat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slugCatName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
