# Generated by Django 2.1.12 on 2019-10-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20191006_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slugName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
