# Generated by Django 2.2.4 on 2019-10-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20191001_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
