# Generated by Django 2.1.12 on 2019-12-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20191011_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='slugTitle',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
